spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/railway
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
  resources:
    static-locations: classpath:/static/

flyway:
  enabled: true
  locations: classpath:db/migration
  init-on-migrate: true